---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "system_file | Data Source | terraform-provider-system"
name: "system_file"
type: "Data Source"
subcategory: ""
description: |-
  system_file retrieves information about a file on the remote system.
---

# Data Source: system_file

`system_file` retrieves information about a file on the remote system.



<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `path` (String) Path to the file. Must be an absolute path.

### Read-Only

- `basename` (String) Base name of the file. Returns the last element of path. Example: Given the attribute `path` is `/path/to/file.txt`, the `basename` is `file.txt`.
- `content` (String) Content of the file. Only recommended for small text-based payloads such as configuration files etc. In a terraform plan,  The content will be stored in plain-text in the terraform state. Mutually exclusive with attributes `content_sensitive` and `source`.
- `content_sensitive` (String, Sensitive) Content of the file similar to `content` attribute but with enabled sensitive flag. Prefer `content_sensitive` to `content` to avoid leak of the content in the terraform log output. Mutually exclusive with attributes `content` and `source`.
- `gid` (Number) ID of the group that owns the file
- `group` (String) Name of the group that owns the file
- `id` (String) ID of the file
- `md5sum` (String) MD5 checksum of the remote file contents on the system in base64 encoding.
- `mode` (String) Permissions of the file in octal format like `755`. Defaults to the umask of the system.
- `uid` (Number) ID of the user who owns the file
- `user` (String) Name of the user who owns the file

